import { documents } from '../data/mockData.js';
import { formatDate, formatCurrency } from '../utils/animations.js';
import { Chart, registerables } from 'chart.js';
import { jsPDF } from 'jspdf';

Chart.register(...registerables);

// All expected vehicle documents in India
const EXPECTED_DOCS = [
  'Registration Certificate (RC)',
  'Motor Insurance (Comprehensive)',
  'Pollution Under Control (PUC)',
  'Driving License',
  'Road Tax Receipt',
  'Fitness Certificate',
  'Emission Certificate',
  'National Permit',
];

const statusConfig = {
  valid: { badge: 'badge--success', label: 'Valid', color: '#10b981' },
  expiring: { badge: 'badge--warning', label: 'Expiring Soon', color: '#f59e0b' },
  expired: { badge: 'badge--danger', label: 'Expired', color: '#dc2626' },
};

/**
 * Generate a branded PDF for a document
 */
function generateDocPDF(doc) {
  const cfg = statusConfig[doc.status];
  const pdf = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  const pageWidth = pdf.internal.pageSize.getWidth();
  const margin = 20;
  let y = 20;

  // ── Header Band ──
  pdf.setFillColor(26, 35, 50); // --color-header
  pdf.rect(0, 0, pageWidth, 40, 'F');

  // Teal accent line
  pdf.setFillColor(13, 148, 136); // --color-primary
  pdf.rect(0, 40, pageWidth, 2, 'F');

  // Brand name
  pdf.setTextColor(255, 255, 255);
  pdf.setFontSize(10);
  pdf.setFont('helvetica', 'bold');
  pdf.text('VEHANTIX', margin, 16);

  pdf.setFontSize(7);
  pdf.setFont('helvetica', 'normal');
  pdf.setTextColor(148, 163, 184); // muted
  pdf.text('Vehicle Document Management', margin, 22);

  // Document title in header
  pdf.setTextColor(255, 255, 255);
  pdf.setFontSize(14);
  pdf.setFont('helvetica', 'bold');
  pdf.text(doc.name, margin, 34);

  y = 52;

  // ── Status Badge ──
  const statusLabel = cfg.label.toUpperCase();
  pdf.setFontSize(9);
  pdf.setFont('helvetica', 'bold');
  const statusWidth = pdf.getTextWidth(statusLabel) + 12;

  // Status background
  const [r, g, b] = hexToRgb(cfg.color);
  pdf.setFillColor(r, g, b);
  pdf.roundedRect(margin, y, statusWidth, 7, 2, 2, 'F');
  pdf.setTextColor(255, 255, 255);
  pdf.text(statusLabel, margin + 6, y + 5);

  y += 18;

  // ── Document Details ──
  pdf.setTextColor(30, 41, 59); // --color-text
  pdf.setFontSize(10);

  const fields = [
    ['Document Name', doc.name],
    ['Issuer', doc.issuer],
    ['Policy / Reference No.', doc.policyNumber],
    ['Valid From', formatDate(doc.validFrom)],
    ['Valid To', doc.validTo ? formatDate(doc.validTo) : 'Lifetime / No Expiry'],
    ['Status', cfg.label],
    ['Key Details', doc.keyDetail],
    ['Contact Number', doc.contactNo || 'N/A'],
  ];

  if (doc.premium !== null && doc.premium !== undefined) {
    fields.push(['Premium / Amount Paid', formatCurrency(doc.premium)]);
  }

  fields.forEach(([label, value]) => {
    // Label
    pdf.setFont('helvetica', 'bold');
    pdf.setTextColor(100, 116, 139); // secondary
    pdf.setFontSize(8);
    pdf.text(label.toUpperCase(), margin, y);
    y += 5;

    // Value
    pdf.setFont('helvetica', 'normal');
    pdf.setTextColor(30, 41, 59);
    pdf.setFontSize(11);
    pdf.text(String(value), margin, y);

    // Separator line
    y += 4;
    pdf.setDrawColor(226, 232, 240);
    pdf.setLineWidth(0.3);
    pdf.line(margin, y, pageWidth - margin, y);
    y += 8;
  });

  // ── Footer ──
  y += 10;
  pdf.setFontSize(7);
  pdf.setFont('helvetica', 'italic');
  pdf.setTextColor(148, 163, 184);
  pdf.text(`Generated by Vehantix on ${new Date().toLocaleDateString('en-IN', { day: 'numeric', month: 'long', year: 'numeric' })}`, margin, y);
  pdf.text('This is a digitally generated document for reference purposes.', margin, y + 5);

  // Bottom teal bar
  const pageHeight = pdf.internal.pageSize.getHeight();
  pdf.setFillColor(13, 148, 136);
  pdf.rect(0, pageHeight - 4, pageWidth, 4, 'F');

  // Download
  const filename = doc.name.replace(/[^a-zA-Z0-9]/g, '_').replace(/_+/g, '_') + '.pdf';
  pdf.save(filename);
}

function hexToRgb(hex) {
  const result = /^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i.exec(hex);
  return result ? [parseInt(result[1], 16), parseInt(result[2], 16), parseInt(result[3], 16)] : [0, 0, 0];
}

/**
 * Show a detail modal for a document
 */
function showDocModal(doc) {
  // Remove existing modal if any
  const existing = document.getElementById('doc-modal');
  if (existing) existing.remove();

  const cfg = statusConfig[doc.status];

  const modal = document.createElement('div');
  modal.id = 'doc-modal';
  modal.className = 'doc-modal-overlay';
  modal.innerHTML = `
    <div class="doc-modal" role="dialog" aria-label="${doc.name}">
      <div class="doc-modal__header">
        <div class="doc-modal__header-text">
          <div class="doc-modal__icon">📄</div>
          <div>
            <h3 class="doc-modal__title">${doc.name}</h3>
            <span class="badge ${cfg.badge}" style="font-size:11px; margin-top:4px; display:inline-block;">${cfg.label}</span>
          </div>
        </div>
        <button class="doc-modal__close" id="doc-modal-close" aria-label="Close">
          <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round">
            <line x1="18" y1="6" x2="6" y2="18"></line>
            <line x1="6" y1="6" x2="18" y2="18"></line>
          </svg>
        </button>
      </div>
      <div class="doc-modal__body">
        <div class="doc-modal__field">
          <span class="doc-modal__label">Issuer</span>
          <span class="doc-modal__value">${doc.issuer}</span>
        </div>
        <div class="doc-modal__field">
          <span class="doc-modal__label">Policy / Reference No.</span>
          <span class="doc-modal__value doc-modal__value--mono">${doc.policyNumber}</span>
        </div>
        <div class="doc-modal__grid">
          <div class="doc-modal__field">
            <span class="doc-modal__label">Valid From</span>
            <span class="doc-modal__value">${formatDate(doc.validFrom)}</span>
          </div>
          <div class="doc-modal__field">
            <span class="doc-modal__label">Valid To</span>
            <span class="doc-modal__value">${doc.validTo ? formatDate(doc.validTo) : 'Lifetime'}</span>
          </div>
        </div>
        <div class="doc-modal__field">
          <span class="doc-modal__label">Key Details</span>
          <span class="doc-modal__value">${doc.keyDetail}</span>
        </div>
        ${doc.contactNo ? `
        <div class="doc-modal__field">
          <span class="doc-modal__label">Contact Number</span>
          <span class="doc-modal__value">
            <a href="tel:${doc.contactNo}" class="doc-modal__phone">📞 ${doc.contactNo}</a>
          </span>
        </div>
        ` : ''}
        ${doc.premium !== null && doc.premium !== undefined ? `
        <div class="doc-modal__field">
          <span class="doc-modal__label">Premium / Amount</span>
          <span class="doc-modal__value doc-modal__value--highlight">${formatCurrency(doc.premium)}</span>
        </div>
        ` : ''}
      </div>
      <div class="doc-modal__footer">
        <button class="doc-modal__btn doc-modal__btn--secondary" id="doc-modal-cancel">Close</button>
        <button class="doc-modal__btn doc-modal__btn--primary" id="doc-modal-download">
          <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
            <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"></path>
            <polyline points="7 10 12 15 17 10"></polyline>
            <line x1="12" y1="15" x2="12" y2="3"></line>
          </svg>
          Download PDF
        </button>
      </div>
    </div>
  `;

  document.body.appendChild(modal);

  // Animate in
  requestAnimationFrame(() => {
    modal.classList.add('doc-modal-overlay--visible');
  });

  // Close handlers
  const closeModal = () => {
    modal.classList.remove('doc-modal-overlay--visible');
    setTimeout(() => modal.remove(), 250);
  };

  modal.querySelector('#doc-modal-close').addEventListener('click', closeModal);
  modal.querySelector('#doc-modal-cancel').addEventListener('click', closeModal);
  modal.addEventListener('click', (e) => {
    if (e.target === modal) closeModal();
  });
  document.addEventListener('keydown', function escHandler(e) {
    if (e.key === 'Escape') {
      closeModal();
      document.removeEventListener('keydown', escHandler);
    }
  });

  // Download handler
  modal.querySelector('#doc-modal-download').addEventListener('click', () => {
    generateDocPDF(doc);
  });
}

export function renderDocuments() {
  const container = document.getElementById('section-documents');

  const availableNames = documents.map(d => d.name);
  const availableCount = availableNames.length;
  const missingDocs = EXPECTED_DOCS.filter(name => !availableNames.includes(name));
  const missingCount = missingDocs.length;
  const totalExpected = EXPECTED_DOCS.length;

  // Compact doc list with action buttons
  const rows = documents
    .map(
      (doc, i) => {
        const cfg = statusConfig[doc.status];
        return `
    <div class="doc-row animate-on-scroll stagger-${i + 1}">
      <div class="doc-row__icon">📄</div>
      <div class="doc-row__info">
        <div class="doc-row__name">${doc.name}</div>
        ${doc.name.includes('Insurance') ? `<div class="doc-row__issuer">${doc.issuer}</div>` : ''}
        <div class="doc-row__detail">${doc.keyDetail}</div>
        <div class="doc-row__validity">📅 ${formatDate(doc.validFrom)} — ${doc.validTo ? formatDate(doc.validTo) : 'Lifetime'}</div>
      </div>
      <div class="doc-row__meta">
        <span class="${cfg.badge} badge" style="font-size:11px;">${cfg.label}</span>
      </div>
      <div class="doc-row__actions">
        <button class="doc-action-btn doc-action-btn--view" data-doc-id="${doc.id}" title="View document details">
          <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
            <path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z"></path>
            <circle cx="12" cy="12" r="3"></circle>
          </svg>
          <span>View</span>
        </button>
        <button class="doc-action-btn doc-action-btn--download" data-doc-id="${doc.id}" title="Download as PDF">
          <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
            <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"></path>
            <polyline points="7 10 12 15 17 10"></polyline>
            <line x1="12" y1="15" x2="12" y2="3"></line>
          </svg>
          <span>PDF</span>
        </button>
      </div>
    </div>
  `;
      }
    )
    .join('');

  // Missing docs list
  const missingItems = missingDocs
    .map(
      (name, i) => `
    <div class="doc-row doc-row--missing animate-on-scroll stagger-${i + availableCount + 1}">
      <div class="doc-row__icon" style="opacity:0.4;">📋</div>
      <div class="doc-row__info">
        <div class="doc-row__name" style="color: var(--color-text-muted);">${name}</div>
        <div class="doc-row__detail" style="color: var(--color-danger);">Not uploaded</div>
      </div>
      <div class="doc-row__meta">
        <span class="badge badge--danger" style="font-size:11px;">Missing</span>
      </div>
      <div class="doc-row__actions">
        <button class="doc-action-btn doc-action-btn--upload" title="Upload ${name}">
          <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
            <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"></path>
            <polyline points="17 8 12 3 7 8"></polyline>
            <line x1="12" y1="3" x2="12" y2="15"></line>
          </svg>
          <span>Upload</span>
        </button>
      </div>
    </div>
  `
    )
    .join('');

  container.innerHTML = `
    <div class="section-header animate-on-scroll">
      <div>
        <span class="section-header__label">FILES</span>
        <h2 class="section-header__title">Vehicle Documents</h2>
      </div>
    </div>

    <div class="docs-overview animate-on-scroll stagger-1">
      <div class="card card--no-hover docs-chart-card">
        <div class="chart-container chart-container--doughnut">
          <canvas id="docs-chart"></canvas>
        </div>
      </div>
      <div class="docs-stats">
        <div class="card card--no-hover docs-stat-card docs-stat-card--available">
          <div class="docs-stat-card__number">${availableCount}</div>
          <div class="docs-stat-card__label">Available</div>
          <div class="docs-stat-card__bar" style="background: var(--color-success);"></div>
        </div>
        <div class="card card--no-hover docs-stat-card docs-stat-card--missing">
          <div class="docs-stat-card__number">${missingCount}</div>
          <div class="docs-stat-card__label">Missing</div>
          <div class="docs-stat-card__bar" style="background: var(--color-danger);"></div>
        </div>
        <div class="card card--no-hover docs-stat-card">
          <div class="docs-stat-card__number">${totalExpected}</div>
          <div class="docs-stat-card__label">Expected</div>
          <div class="docs-stat-card__bar" style="background: var(--color-primary);"></div>
        </div>
      </div>
    </div>

    <div class="doc-list">
      ${rows}
      ${missingItems}
    </div>
  `;

  // ── Attach event listeners ──
  container.querySelectorAll('.doc-action-btn--view').forEach(btn => {
    btn.addEventListener('click', () => {
      const doc = documents.find(d => d.id === btn.dataset.docId);
      if (doc) showDocModal(doc);
    });
  });

  container.querySelectorAll('.doc-action-btn--download').forEach(btn => {
    btn.addEventListener('click', () => {
      const doc = documents.find(d => d.id === btn.dataset.docId);
      if (doc) generateDocPDF(doc);
    });
  });

  // ── Render Doughnut Chart ──
  const ctx = document.getElementById('docs-chart').getContext('2d');

  // Center text plugin
  const centerTextPlugin = {
    id: 'centerText',
    afterDraw(chart) {
      const { width, height, ctx: c } = chart;
      c.save();
      c.textAlign = 'center';
      c.textBaseline = 'middle';
      const centerX = width / 2;
      const centerY = height / 2;

      // Large number
      c.font = "700 28px 'Inter', sans-serif";
      c.fillStyle = '#1e293b';
      c.fillText(`${availableCount}/${totalExpected}`, centerX, centerY - 8);

      // Small label
      c.font = "500 11px 'Inter', sans-serif";
      c.fillStyle = '#94a3b8';
      c.fillText('Documents', centerX, centerY + 16);

      c.restore();
    },
  };

  new Chart(ctx, {
    type: 'doughnut',
    data: {
      labels: ['Available', 'Missing'],
      datasets: [
        {
          data: [availableCount, missingCount],
          backgroundColor: ['#10b981', 'rgba(220, 38, 38, 0.2)'],
          borderColor: ['#10b981', '#dc2626'],
          borderWidth: [0, 1.5],
          hoverBackgroundColor: ['#059669', 'rgba(220, 38, 38, 0.35)'],
          spacing: 3,
          borderRadius: 4,
        },
      ],
    },
    options: {
      responsive: true,
      maintainAspectRatio: true,
      cutout: '72%',
      plugins: {
        legend: { display: false },
        tooltip: {
          backgroundColor: 'rgba(26, 35, 50, 0.92)',
          titleFont: { family: 'Inter', size: 12, weight: '600' },
          bodyFont: { family: 'Inter', size: 12 },
          padding: 12,
          cornerRadius: 8,
          callbacks: {
            label: (ctx) => ` ${ctx.label}: ${ctx.parsed} documents`,
          },
        },
      },
    },
    plugins: [centerTextPlugin],
  });
}
