import { documents } from '../data/mockData.js';
import { formatDate, formatCurrency } from '../utils/animations.js';
import { Chart, registerables } from 'chart.js';
import { jsPDF } from 'jspdf';

Chart.register(...registerables);

// All expected vehicle documents in India
const EXPECTED_DOCS = [
  'Registration Certificate (RC)',
  'Motor Insurance (Comprehensive)',
  'Pollution Under Control (PUC)',
  'Driving License',
  'Road Tax Receipt',
  'Fitness Certificate',
  'Emission Certificate',
  'National Permit',
];

const statusConfig = {
  valid: { badge: 'badge--success', label: 'Valid', color: '#10b981' },
  expiring: { badge: 'badge--warning', label: 'Expiring Soon', color: '#f59e0b' },
  expired: { badge: 'badge--danger', label: 'Expired', color: '#dc2626' },
};

/**
 * Generate a branded PDF for a document
 */
function generateDocPDF(doc) {
  const cfg = statusConfig[doc.status];
  const pdf = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  const pageWidth = pdf.internal.pageSize.getWidth();
  const margin = 20;
  let y = 20;

  // ── Header Band ──
  pdf.setFillColor(26, 35, 50); // --color-header
  pdf.rect(0, 0, pageWidth, 40, 'F');

  // Teal accent line
  pdf.setFillColor(13, 148, 136); // --color-primary
  pdf.rect(0, 40, pageWidth, 2, 'F');

  // Brand name
  pdf.setTextColor(255, 255, 255);
  pdf.setFontSize(10);
  pdf.setFont('helvetica', 'bold');
  pdf.text('VEHANTIX', margin, 16);

  pdf.setFontSize(7);
  pdf.setFont('helvetica', 'normal');
  pdf.setTextColor(148, 163, 184); // muted
  pdf.text('Vehicle Document Management', margin, 22);

  // Document title in header
  pdf.setTextColor(255, 255, 255);
  pdf.setFontSize(14);
  pdf.setFont('helvetica', 'bold');
  pdf.text(doc.name, margin, 34);

  y = 52;

  // ── Status Badge ──
  const statusLabel = cfg.label.toUpperCase();
  pdf.setFontSize(9);
  pdf.setFont('helvetica', 'bold');
  const statusWidth = pdf.getTextWidth(statusLabel) + 12;

  // Status background
  const [r, g, b] = hexToRgb(cfg.color);
  pdf.setFillColor(r, g, b);
  pdf.roundedRect(margin, y, statusWidth, 7, 2, 2, 'F');
  pdf.setTextColor(255, 255, 255);
  pdf.text(statusLabel, margin + 6, y + 5);

  y += 18;

  // ── Document Details ──
  pdf.setTextColor(30, 41, 59); // --color-text
  pdf.setFontSize(10);

  const fields = [
    ['Document Name', doc.name],
    ['Issuer', doc.issuer],
    ['Policy / Reference No.', doc.policyNumber],
    ['Valid From', formatDate(doc.validFrom)],
    ['Valid To', doc.validTo ? formatDate(doc.validTo) : 'Lifetime / No Expiry'],
    ['Status', cfg.label],
    ['Key Details', doc.keyDetail],
    ['Contact Number', doc.contactNo || 'N/A'],
  ];

  if (doc.premium !== null && doc.premium !== undefined) {
    fields.push(['Premium / Amount Paid', formatCurrency(doc.premium)]);
  }

  fields.forEach(([label, value]) => {
    // Label
    pdf.setFont('helvetica', 'bold');
    pdf.setTextColor(100, 116, 139); // secondary
    pdf.setFontSize(8);
    pdf.text(label.toUpperCase(), margin, y);
    y += 5;

    // Value
    pdf.setFont('helvetica', 'normal');
    pdf.setTextColor(30, 41, 59);
    pdf.setFontSize(11);
    pdf.text(String(value), margin, y);

    // Separator line
    y += 4;
    pdf.setDrawColor(226, 232, 240);
    pdf.setLineWidth(0.3);
    pdf.line(margin, y, pageWidth - margin, y);
    y += 8;
  });

  // ── Footer ──
  y += 10;
  pdf.setFontSize(7);
  pdf.setFont('helvetica', 'italic');
  pdf.setTextColor(148, 163, 184);
  pdf.text(`Generated by Vehantix on ${new Date().toLocaleDateString('en-IN', { day: 'numeric', month: 'long', year: 'numeric' })}`, margin, y);
  pdf.text('This is a digitally generated document for reference purposes.', margin, y + 5);

  // Bottom teal bar
  const pageHeight = pdf.internal.pageSize.getHeight();
  pdf.setFillColor(13, 148, 136);
  pdf.rect(0, pageHeight - 4, pageWidth, 4, 'F');

  // Download
  const filename = doc.name.replace(/[^a-zA-Z0-9]/g, '_').replace(/_+/g, '_') + '.pdf';
  pdf.save(filename);
}

function hexToRgb(hex) {
  const result = /^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i.exec(hex);
  return result ? [parseInt(result[1], 16), parseInt(result[2], 16), parseInt(result[3], 16)] : [0, 0, 0];
}

/**
 * Show a detail modal for a document
 */
function showDocModal(doc) {
  // Remove existing modal if any
  const existing = document.getElementById('doc-modal');
  if (existing) existing.remove();

  const cfg = statusConfig[doc.status];

  const modal = document.createElement('div');
  modal.id = 'doc-modal';
  modal.className = 'doc-modal-overlay';
  modal.innerHTML = `
    <div class="doc-modal" role="dialog" aria-label="${doc.name}">
      <div class="doc-modal__header">
        <div class="doc-modal__header-text">
          <div class="doc-modal__icon">📄</div>
          <div>
            <h3 class="doc-modal__title">${doc.name}</h3>
            <span class="badge ${cfg.badge}" style="font-size:11px; margin-top:4px; display:inline-block;">${cfg.label}</span>
          </div>
        </div>
        <button class="doc-modal__close" id="doc-modal-close" aria-label="Close">
          <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round">
            <line x1="18" y1="6" x2="6" y2="18"></line>
            <line x1="6" y1="6" x2="18" y2="18"></line>
          </svg>
        </button>
      </div>
      <div class="doc-modal__body">
        <div class="doc-modal__field">
          <span class="doc-modal__label">Issuer</span>
          <span class="doc-modal__value">${doc.issuer}</span>
        </div>
        <div class="doc-modal__field">
          <span class="doc-modal__label">Policy / Reference No.</span>
          <span class="doc-modal__value doc-modal__value--mono">${doc.policyNumber}</span>
        </div>
        <div class="doc-modal__grid">
          <div class="doc-modal__field">
            <span class="doc-modal__label">Valid From</span>
            <span class="doc-modal__value">${formatDate(doc.validFrom)}</span>
          </div>
          <div class="doc-modal__field">
            <span class="doc-modal__label">Valid To</span>
            <span class="doc-modal__value">${doc.validTo ? formatDate(doc.validTo) : 'Lifetime'}</span>
          </div>
        </div>
        <div class="doc-modal__field">
          <span class="doc-modal__label">Key Details</span>
          <span class="doc-modal__value">${doc.keyDetail}</span>
        </div>
        ${doc.contactNo ? `
        <div class="doc-modal__field">
          <span class="doc-modal__label">Contact Number</span>
          <span class="doc-modal__value">
            <a href="tel:${doc.contactNo}" class="doc-modal__phone">📞 ${doc.contactNo}</a>
          </span>
        </div>
        ` : ''}
        ${doc.premium !== null && doc.premium !== undefined ? `
        <div class="doc-modal__field">
          <span class="doc-modal__label">Premium / Amount</span>
          <span class="doc-modal__value doc-modal__value--highlight">${formatCurrency(doc.premium)}</span>
        </div>
        ` : ''}
      </div>
      <div class="doc-modal__footer">
        <button class="doc-modal__btn doc-modal__btn--secondary" id="doc-modal-cancel">Close</button>
        <button class="doc-modal__btn doc-modal__btn--primary" id="doc-modal-download">
          <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
            <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"></path>
            <polyline points="7 10 12 15 17 10"></polyline>
            <line x1="12" y1="15" x2="12" y2="3"></line>
          </svg>
          Download PDF
        </button>
      </div>
    </div>
  `;

  document.body.appendChild(modal);

  // Animate in
  requestAnimationFrame(() => {
    modal.classList.add('doc-modal-overlay--visible');
  });

  // Close handlers
  const closeModal = () => {
    modal.classList.remove('doc-modal-overlay--visible');
    setTimeout(() => modal.remove(), 250);
  };

  modal.querySelector('#doc-modal-close').addEventListener('click', closeModal);
  modal.querySelector('#doc-modal-cancel').addEventListener('click', closeModal);
  modal.addEventListener('click', (e) => {
    if (e.target === modal) closeModal();
  });
  document.addEventListener('keydown', function escHandler(e) {
    if (e.key === 'Escape') {
      closeModal();
      document.removeEventListener('keydown', escHandler);
    }
  });

  // Download handler
  modal.querySelector('#doc-modal-download').addEventListener('click', () => {
    generateDocPDF(doc);
  });
}

export function renderDocuments() {
  const container = document.getElementById('section-documents');

  const availableNames = documents.map(d => d.name);
  const availableCount = availableNames.length;
  const missingDocs = EXPECTED_DOCS.filter(name => !availableNames.includes(name));
  const missingCount = missingDocs.length;
  const totalExpected = EXPECTED_DOCS.length;

  // Compact doc list with action buttons
  const rows = documents
    .map(
      (doc, i) => {
        const cfg = statusConfig[doc.status];
        return `
    <div class="card animate-on-scroll stagger-${i + 1}" style="display:flex; flex-direction:column; gap:16px;">
      <div style="display:flex; justify-content:space-between; align-items:flex-start;">
        <div style="display:flex; gap:12px; align-items:center;">
          <div class="doc-row__icon" style="background:var(--color-primary-light); color:var(--color-primary-dark);">📄</div>
          <div>
            <div class="doc-row__name">${doc.name}</div>
            ${doc.name.includes('Insurance') ? `<div class="doc-row__issuer" style="margin-top:2px;">${doc.issuer}</div>` : ''}
          </div>
        </div>
        <span class="${cfg.badge} badge" style="font-size:11px; white-space:nowrap; flex-shrink:0;">${cfg.label}</span>
      </div>
      <div style="flex:1;">
        <div class="doc-row__validity" style="margin-bottom:8px; font-weight:500;">📅 Valid: ${formatDate(doc.validFrom)} — ${doc.validTo ? formatDate(doc.validTo) : 'Lifetime'}</div>
        <div class="doc-row__detail" style="white-space:normal; overflow:hidden; display:-webkit-box; -webkit-line-clamp:2; -webkit-box-orient:vertical;">${doc.keyDetail}</div>
      </div>
      <div class="doc-row__actions" style="margin-top:auto; display:flex; gap:8px; width:100%;">
        <button class="doc-action-btn doc-action-btn--view" data-doc-id="${doc.id}" title="View document details" style="flex:1; justify-content:center; background:rgba(13,148,136,0.1); color:var(--color-primary-dark); border:none;">
          <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
            <path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z"></path>
            <circle cx="12" cy="12" r="3"></circle>
          </svg>
          <span>View</span>
        </button>
        <button class="doc-action-btn doc-action-btn--download" data-doc-id="${doc.id}" title="Download as PDF" style="flex:1; justify-content:center; background:var(--color-surface-hover); border:1px solid var(--color-border); color:var(--color-text);">
          <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
            <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"></path>
            <polyline points="7 10 12 15 17 10"></polyline>
            <line x1="12" y1="15" x2="12" y2="3"></line>
          </svg>
          <span>PDF</span>
        </button>
      </div>
    </div>
  `;
      }
    )
    .join('');

  // Missing docs list
  const missingItems = missingDocs
    .map(
      (name, i) => `
    <div class="card doc-row--missing animate-on-scroll stagger-${i + availableCount + 1}" style="display:flex; flex-direction:column; gap:16px;">
      <div style="display:flex; justify-content:space-between; align-items:flex-start;">
        <div style="display:flex; gap:12px; align-items:center;">
          <div class="doc-row__icon" style="opacity:0.4;">📋</div>
          <div>
            <div class="doc-row__name" style="color: var(--color-text-muted);">${name}</div>
          </div>
        </div>
        <span class="badge badge--danger" style="font-size:11px; white-space:nowrap; flex-shrink:0;">Missing</span>
      </div>
      <div style="flex:1;">
        <div class="doc-row__detail" style="color: var(--color-danger); white-space:normal;">This document has not been uploaded yet.</div>
      </div>
      <div class="doc-row__actions" style="margin-top:auto; display:flex; width:100%;">
        <button class="doc-action-btn doc-action-btn--upload" title="Upload ${name}" style="flex:1; justify-content:center; background:var(--color-header); color:#fff; border:none;">
          <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
            <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"></path>
            <polyline points="17 8 12 3 7 8"></polyline>
            <line x1="12" y1="3" x2="12" y2="15"></line>
          </svg>
          <span>Upload</span>
        </button>
      </div>
    </div>
  `
    )
    .join('');

  container.innerHTML = `
    <div class="section-header animate-on-scroll">
      <div>
        <span class="section-header__label">FILES</span>
        <h2 class="section-header__title">Vehicle Documents</h2>
      </div>
      <div style="margin-left:auto; display:flex; gap:12px; align-items:center;">
        <span class="badge badge--outline" style="font-size:12px; font-weight:600;">${availableCount} / ${totalExpected} Uploaded</span>
        ${missingCount > 0 ? `<span class="badge badge--danger" style="font-size:12px; font-weight:600;">${missingCount} Missing Action Required</span>` : '<span class="badge badge--success" style="font-size:12px; font-weight:600;">All complete</span>'}
      </div>
    </div>

    <div class="doc-list">
      ${rows}
      ${missingItems}
    </div>
  `;

  // ── Attach event listeners ──
  container.querySelectorAll('.doc-action-btn--view').forEach(btn => {
    btn.addEventListener('click', () => {
      const doc = documents.find(d => d.id === btn.dataset.docId);
      if (doc) showDocModal(doc);
    });
  });

  container.querySelectorAll('.doc-action-btn--download').forEach(btn => {
    btn.addEventListener('click', () => {
      const doc = documents.find(d => d.id === btn.dataset.docId);
      if (doc) generateDocPDF(doc);
    });
  });
}
